In [ ]:
#import ast,sys
input_str = "bchhihlaatit#i#s#g#a#r#h"
#Type your code here
input_str = input_str.strip()
input_str = input_str.replace(" ","")
message1 = ""
for i in range(len(input_str)):
    if i%2==0:
        message1 = message1+input_str[i]

message2 = ""
j=1
for j in range(len(input_str)):
    if j%2==1:
        message2 =message2+input_str[j]
        
message1 = message1.rstrip("#")
message2 = message2.rstrip("#")

print(message1+','+message2)

bhilai,chhattisgarh

In [ ]:
mass = input("Enter Mass: ")
acc = input("Enter Acceleration: ")
mass = float(mass)
acc = float(acc)
force = mass*acc
print("Calculated force is",force,"N.")

Enter Mass: 2
Enter Acceleration: 4
Calculated force is 8.0 N.

In [ ]:
Name = "Dhaval"
Age = 26
Height = 5.11
Not_Indian = False
print(type(Name))
print(type(Age))
print(type(Height))
print(type(Not_Indian))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [ ]:
#printf method

car_name = "honda"
print(f"Your car name is {car_name}!")

Your car name is honda!

In [ ]:
# extend()
L = ["Chemistry", "Biology", [1989,  2004] ,("Oreily" , "Pearson")]
L.extend([5, 8])
L

['Chemistry', 'Biology', [1989, 2004], ('Oreily', 'Pearson'), 5, 8]

In [ ]:
# append()
L = ["Chemistry", "Biology", [1989,  2004], ("Oreily" , "Pearson")]
L.append([5, 8])
L

['Chemistry', 'Biology', [1989, 2004], ('Oreily', 'Pearson'), [5, 8]]

In [ ]:
L = ['Chemistry', 'Biology', [1989, 2004], ('Oreily', 'Pearson'), 5, 8]
L.pop()

8

In [ ]:
L

['Chemistry', 'Biology', [1989, 2004], ('Oreily', 'Pearson'), 5]

In [ ]:
L.remove("Biology")
L

['Chemistry', [1989, 2004], ('Oreily', 'Pearson'), 5]

In [ ]:
input_list = ['SAS', 'R', 'PYTHON', 'SPSS']
# Write code to remove 'SPSS'
input_list.remove('SPSS')
# Write code to append 'SPARK'
input_list.append("SPARK")
print(input_list)

['SAS', 'R', 'PYTHON', 'SPARK']

In [ ]:
input_str =  ['Pythons syntax is easy to learn', 'Pythons syntax is very clear']

string_1 = input_str[0]+" & "+input_str[1]#Type your answer here
print(string_1)

Pythons syntax is easy to learn & Pythons syntax is very clear

In [ ]:
A = [3,2,1]
B=A
print(A,B)

[3, 2, 1] [3, 2, 1]

In [ ]:
A[0]=4
print(A,B)

[4, 2, 1] [4, 2, 1]

In [ ]:
C=[3,2,1]
D = C[:]
print(C,D)

[3, 2, 1] [3, 2, 1]

In [ ]:
C[0]=4
print(C,D)

[4, 2, 1] [3, 2, 1]

In [ ]:
input_str = 'Kumar_Ravi_003'
data = input_str.split("_")
first_name = data[1] #write your answer here
second_name = data[0] #write your answer here
customer_code = data[2] #write your answer here
print(first_name)
print(second_name)
print(customer_code)

Ravi
Kumar
003

In [ ]:
word = ['1','2','3','4']
word[ : ] = [ ] 
print(word)

[]

In [ ]:
L = ['one','two','three', 'four', 'five', 'six']
print(sorted(L))
print (L)

['five', 'four', 'one', 'six', 'three', 'two']
['one', 'two', 'three', 'four', 'five', 'six']

In [ ]:
t = 1,4,7,3,5,2,6
t
sorted(t)

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
t = 1,4,7,3,5,2,6
r = sorted(t)
s = tuple(r)
print(s)

(1, 2, 3, 4, 5, 6, 7)

In [ ]:
input_tuple = ('Monty Python', 'British', 1969)

# Write your code here
temp_list= list(input_tuple)
temp_list.append("Python")
tuple_2 = tuple(temp_list)

# Make sure to name the final tuple 'tuple_2'
print(tuple_2)

('Monty Python', 'British', 1969, 'Python')

In [ ]:
Grades = ["A", "A", "B", "C", "D", "B", "B", "C", "D", "E", "C", "C", "A", "B", "F", "D", "C", "B", "C", "A", "B", "F", "B", "A", "E", "B", "B", "C", "D"]

set(Grades)

{'A', 'B', 'C', 'D', 'E', 'F'}

In [ ]:
list_1 = [5, 1, 3, 4, 4, 5, 6, 7]
list_2 = [3, 3, 5, 5, 1 ,7 ,2]

#Type your answer here

A = set(list_1)
B = set(list_2)
C = A.intersection(B)

answer = list(C)

print(answer)

[1, 3, 5, 7]

In [ ]:
input_dict = { 101:['Shiva', 24, 'Content Strategist'] ,102:['Udit',25,'Content Strategist'], 103:['Sonam', 28,'Sr Manager'], 104:['Ansari',29,'Product Lead' ],105:['Huzefa',32,'Project Manager' ]}

#Type you answer here
L = input_dict[104]
profession = L[2]

print(profession)

Product Lead

In [ ]:
input_dict = {'Name': 'Monty', 'Profession': 'Singer', 'Python': 'Monty' }


# Type your answer here
L = input_dict.keys()
L = list(L)
flag = ("Python" in L)

if flag ==False: answer = "NA"
else: answer = input_dict["Python"]
print(answer)

Monty

In [ ]:
input_d = {'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}

L= input_d.values()

L= list(L)

print(sorted(L))

['Amazon', 'Apple', 'RJIO', 'Twitter']

In [ ]:
input_str = " "

if input_str[0] in ['a', 'e', 'i' ,'o', 'u','A','E','I','O','U']:
  print("YES")
else:
  print("NO")

NO

In [ ]:
input_list = ['VARMA', 'raj', 'Gupta', 'SaNdeeP']

for i in range(len(input_list)):
  input_list[i]= input_list[i].capitalize()

print(input_list)

['Varma', 'Raj', 'Gupta', 'Sandeep']

In [ ]:
#to find perfect squares
import math
n=4
L = []

for i in range (1, n**2+1):
  if (math.sqrt(i) == int(math.sqrt(i))):
    L.append(i)

L

[1, 4, 9, 16]

In [ ]:
input_list = ['wood','old','apple','big','item','euphoria']

list_vowel = []

for i in range(len(input_list)):
  if input_list[i][0] in ['a', 'e', 'i' ,'o', 'u','A','E','I','O','U']:
    list_vowel.append(input_list[i])

print(list_vowel)
#if input_str[0] in ['a', 'e', 'i' ,'o', 'u','A','E','I','O','U']:
#  print("YES")
#else:
#  print("NO")

['old', 'apple', 'item', 'euphoria']

In [ ]:
x = 6
y = 7

def squared(a,b):
  product = 1
  for i in range(1,b+1):
    product = product*a
  
  return product

print(squared(x,y))

279936

In [ ]:
a = 9
b = 3

greater = lambda x,y: x if x>y else y

print(greater(a,b))

9

In [ ]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

9996

In [ ]:
students_data = {1:['Sam', 15] , 2:['Rob',18], 3:['Kyle', 16], 4:['Cornor',19], 5:['Trump',20]}

len(list(filter(lambda x : x[1] > 18, students_data.values())))

2

In [ ]:
input_list = ['Santa Cruz','Santa fe','Mumbai','Delhi']

count = len(list(filter(lambda x:x[0] =='S', input_list)))

print(count)

2

In [ ]:
first_name = ['Ankur', 'Avik', 'Kiran', 'Nitin']
last_name = ['Narang', 'Sarkar', 'R', 'Sareen']
name = []
name = list(map(lambda x,y: x+" "+y, first_name,last_name))
print(name)

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']

In [ ]:
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

list_answer = list(filter(lambda x: x % 5 ==0, input_list))

print(list_answer)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [ ]:
input_list = ['soap','sharp','shy','silent','ship','summer','sheep']

sp = list(filter(lambda x: x[0]=='s' and x[-1]=='p', input_list))

print(sp)

['soap', 'sharp', 'ship', 'sheep']

In [ ]:
from functools import reduce

input_list = ['All','you','have','to','fear','is','fear','itself']

answer = reduce(lambda x,y:x+' '+y, input_list)

print(answer)

All you have to fear is fear itself

In [ ]:
from functools import reduce

input_list = [65,76,87,23,12,90,99]

answer = reduce(max, input_list)

print(answer)

99

In [ ]:
for i in range(3):
    print(i)

0
1
2

In [ ]:
a=11

b=12

c=13 

d=14

print(f'{a}{b}{c}')

print(d)

111213
14

In [ ]:
in_string=input()

#here extract the two numbers from the string
string = in_string.split(',')
x = int(string[0])
y = int(string[1])


#print x and y before swapping
print("x before swapping: ",x)
print("y before swapping: ",y)

#Writing your swapping code here
z=x
x=y
y=z

#print x and y after swapping
print("\nx after swapping: ",x)
print("y after swapping: ",y)

In [ ]:
#3n+1 - beautiful
#3n+2 - pretty
#3n - sexy

k=int(input())

answer = k % 3

if answer == 2:
  print("pretty")
elif answer == 1:
  print("beautiful")
else:
  print("sexy")

In [ ]:
#Take input here
#we will take input using ast sys
import ast
input_str = input()

#ast.literal_eval() will evaluate the string and make a data structure for the same
#here the input is a list since input is in '[...]', so ast.literal_eval() will
#make a list with the same data as passed
input_list = ast.literal_eval(input_str)

#the data or the two values in list is now changed to separate variables
day_of_the_week = input_list[0] #first element is an integer denoting the day of the week
is_on_vacation = input_list[1] #this is a boolean denoting if its vacation or not

# write your code here

def alarm_time(day_of_the_week, is_on_vacation):
  weekend = [6,7]
  if is_on_vacation:
    if day_of_the_week not in weekend:
      return "10:00"
    else:
      return "off"
  else:
    if day_of_the_week not in weekend:
      return "7:00"
    else:
      return "10:00"

print(alarm_time(day_of_the_week, is_on_vacation))

In [ ]:
number=int(input())



#the function definition starts here
def factorial(n):
    #write the funtion here that finds and RETURNS factorial of next
    prod = 1
    for i in range(1,n+1):
       prod = prod *i
    
    return prod
    
    


#function definition ends here

#do not alter the code typed below
k=factorial(number)
print(k)

In [ ]:
number=int(input())
from functools import reduce


#the function definition starts here
def factorial(n):
    #write the funtion here that finds and RETURNS factorial of next
    if n == 0:
      return 1
    elif n<0:
      return -1
    else:
      return reduce(lambda x,y:x*y, range(1,n+1))
    
    


#function definition ends here

#do not alter the code typed below
k=factorial(number)
print(k)

In [ ]:
number=int(input())
rev=0
n = number
while (n>0):
  rev = rev*10 + n%10
  n = n//10

print(rev)

In [ ]:
import ast
input_str = input()
my_list = ast.literal_eval(input_str)

m = my_list[0]
c = my_list[1]

choc = m//c
w = m//c

while w//3!=0:
  choc = choc + w//3
  w = w//3 + w % 3

print(choc)

In [ ]:
n = int(input())

for i in range(n):
  for j in range(n-i-1):
    print(" ",end='')
  for k in range(i):
    print("*_",end='')
  print("*")

In [ ]:
#Take input here
#we will take input using ast sys
import ast
input_str = input()
input_list = ast.literal_eval(input_str)

#Remember how we took input in the Alarm clock Question in previous Session?
#Lets see if you can finish taking input on your own

data= input_list[0]
check= input_list[1]

#start writing your code to find if check is above average of data 
avg = sum(data)/len(data)

if check>avg:
    print("True")
else:
    print("False")

In [ ]:
import ast
team = ast.literal_eval(input())
applicants = ast.literal_eval(input())

#write your code here
def eligibility(data, check):
  avg = sum(data)/len(data)
  if check>avg:
    return 1
  else:
    return 0

for cand in applicants:
  if(eligibility(team, cand)):
    team.append(cand)

print(team)

Calendar
Description
You are planning to go to your friend's wedding and you have long events all month, lasting at least a few days. You have the start and end dates of events and your task is to find out events overlapping with the wedding date.

The code for taking input has already been written for you, please don't modify that, but do read and try to understand the way input has been taken. You will be asked to take input on your own for most of the problems here onwards. Taking data in a suitable format is an important skill for a Data Scientist.

----------------------------------------------------------------------
Input:
The input will contain a list of lists where each sub-list has only two elements representing the start and end date of an event, the start date will be less than or equal to the end date. The next line of input will have a wedding date. 

Output:
The output should have the number of events overlapping with the wedding date.

----------------------------------------------------------------------
Sample input:
[ [29,31], [23,26], [24,25] ]
24

Sample output:
2

Explanation:
There are three events in the month.
Event 1= from date 29 to 31
Event 2= from date 23 to 26
Event 3= from date 24 to 25
Wedding is on 24. This means it will clash with Event 3 and Event 2, that is two events. The output is therefore 2.

----------------------------------------------------------------------
Sample input:
[ [1, 4], [7, 10], [8, 8], [14, 23] ]
26

Sample output:
0

In [ ]:
import ast
events = ast.literal_eval(input())
wedding = int(input())

count = 0

for event in events:
  if wedding >= event[0] and wedding <= event [1]:
    count = count + 1

print(count)

In [ ]:
import ast
input_list = ast.literal_eval(input())

m = input_list[0]
n = input_list[1]

mat = [0]*n

mat = [list(mat) for i in range(m)]

#print(mat)

for i in range(m):
  for j in range(n):
    if i==0 or j==0 or i==m-1 or j==n-1:
      mat[i][j] = 1

for k in mat:
  print(k)

In [ ]:
print(chr(51))

In [ ]:
s = input()

s = s.lower()

r = ""

for i in s:
  r = i + r

if r == s:
  print(1)
else:
  print(0)

In [ ]:
sentence=input()

words = sentence.split(' ')

words.reverse()

final = ' '.join(words)

print(final)

In [ ]:
sentence=input()

sentence = sentence.lower()
words = sentence.split()

new=[]
#new = [word[0].upper() + word[1:] for word in words]
new = [word.title() for word in words]

final = '_'.join(new)

print(final)

In [ ]:
s = input()

vowel = "aeiouAEIOU"

v=''
c=''

for i in s:
  if i in vowel:
    v=v+i
  else:
    c=c+i

final = v+c
print(final)

In [ ]:
s1 = input()
s2 = input()

s1 = s1.lower()
s2 = s2.lower()

count = min(len(s1), len(s2))

prefix = ''

for i in range(0,count):
  if s1[i] != s2[i]:
    break
  else:
    prefix = prefix + s1[i]

if(len(prefix)) == 0:
  print(-1)
else:
  print(prefix)

In [ ]:
s1 = input()
s2 = input()

s1 = s1.lower()
s2 = s2.lower()

flag = False

if len(s1) == len(s2):
  for i in range(len(s1)):
    if s1[i] in s2:
      flag = True
    else:
      flag = False
      break
else:
  flag = False

print(flag)

In [ ]:
import ast
input_list = ast.literal_eval(input())

answer = set(input_list)

answer_list = list(answer)

print(answer_list)

In [ ]:
import ast
input_list = ast.literal_eval(input())

answer_list = []

for i in input_list:
  if i not in answer_list:
    answer_list.append(i)

print(answer_list)

In [ ]:
import ast
input_str = input()
#input dictionary has been received in input_dict
input_dict = ast.literal_eval(input_str)

for key in input_dict.keys():
  for word in input_dict[key]:
    print(key+'_'+word)

upGrad String
Description
For the purpose of this question, we will define something called an upGrad string. Note that this definition is not valid outside this question. A string upGrad string if the frequency of its characters is something like 1, 2, 3, 4, .... That is a character appears only once, another appears twice, another appears thrice and so on. For example string '$yrr$ssrsr' is a upGrad string since the frequency of y:1, $:2, s:3, r:4, however string '$yrr$ssrsr%' will not be an upGrad string since it has two characters (y and %) with frequency 1. The frequency of characters should be of form 1, 2, 3, 4, 5... only.

Given a string, can you determine if the string is upGrad string or no?





Input:

A string



Output:

Boolean depending whether the string is upGrad string or not





Sample input:

$yrr$ssrsr



Sample output:

True





Sample input:

$yrr$ssrsr%



Sample output:

False



Sample input:

ab#ab#aba



Sample output:

False



Sample input:

ab#ab#ab6a



Sample output:

True

In [ ]:
import ast

input_str = input()

mydict = {}

for i in input_str:
  if i not in mydict:
    mydict[i] = 1
  else:
    mydict[i] = mydict[i] + 1

n_times = len(mydict)
flag = True

for i in range (1,n_times+1):
  if i not in mydict.values():
    flag = False
    break

print(flag)

In [ ]:
#brackets balanced 

import ast

input_str = input()

stack = []

for i in input_str:
  if len(stack) == 0:
    stack.append(i)
  else:
    if i == ')' and stack[-1] == '(':
      stack.pop()
    elif i == '}' and stack[-1] == '{':
      stack.pop()
    elif i == ']' and stack[-1] == '[':
      stack.pop()
    else:
      stack.append(i)

if stack:
  print('No')
else:
  print('Yes')

In [ ]:
#MCQ

((500//7) % 5) ** 3

In [ ]:
S ='I love Python'

S[-11:-7]

In [ ]:
3*3**3

In [ ]:
T = (3, 5, 7, 11)
T.append(9)

In [ ]:
L1 = ['Vikas', 'Akshay', 'Sanskar', 'Mahima']
print(L1[1][-1])

In [ ]:
l = [32, 34, 12, 27, 33]
l.append([14, 19])
print(len(l))

In [ ]:
D = {1:['Raj', 22], 2:['Simran', 21], 3:['Rahul', 40]}
for val in D:
     print(val)

In [ ]:
print(list(range(10, 1, -1)))

Extracting Elements from Array
Description
From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.



Input format:

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



Output format:

1-D array containing integers greater than 'm' and smaller than 'n'.





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ] (array)

6 (m)

12 (n)



Sample output:

[ 9 7 9 ]





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ]

12

6



Sample output:

[ ]

In [ ]:
#take input here
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list) #start writing your code from here
final_array = array_1[array_1 > m]
final_array = final_array[final_array < n]#start writing your code from here

print(final_array)

Description
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:
Input 1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]

In [ ]:
# Read the input list
import ast,sys
input_str = input()
input_list = ast.literal_eval(input_str)

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last = array_2d[:,-1]
row_last = array_2d[-1,:]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

In [ ]:
# Read the variable from STDIN
n = int(input())

import numpy as np

# Create an 'n*n' array of all ones
#mat  = np.ones((n,n), dtype = int) or
mat  = np.full((n,n), 1)
# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
for i in range(1, n-1):
  for j in range(1, n-1):
    mat[i][j] = 0
# Print the array created
print(mat)

Stacking arrays


Description
Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]



Input:

Array 1: 3*3

[[7, 13, 14]

[18, 10, 17]

[11, 12, 19]]



Array 2: 1-D array

[16, 6, 1]



Array 3: 1*4 array

[[5, 8, 4, 3]]



Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]

In [ ]:
# Read the input
import ast
input_list = [[[7, 13, 14], [18, 10, 17], [11, 12, 19]], [16, 6, 1], [[5, 8, 4, 3]]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

# Import NumPy
import numpy as np

# Write your code here
mat1 = np.array(list_1)
mat2 = np.array(list_2)
mat3 = np.array(list_3)
m = np.transpose(mat3)

mat4 = np.vstack((mat1,mat2))
final_array = np.hstack((mat4,m))
print(final_array)

In [ ]:
import datetime as dt
import os
import requests

user_api = os.environ ['current_weather_data']
location = input ("Enter the City name:")

api_key = "4062a7aec554d5d6d7cac94861c9c61b"

complete_api_link = "http://api.openweathermap.org/data/2.5/weather?"

api_link= requests.get(complete_api_link)
api_data = api_link.json()




CITY = (input("Enter city name:"))

def kelvin_to_celsius_fahrenheit(kelvin):
  celsius = kelvin - 273.15
  fahrenheit = celsius * (9/5) + 32
  return celsius, fahrenheit


url = url + "appid=" + api_key + "&q=" + CITY
response = requests.get(url).json()

temp_kelvin = response['main']['temp']
temp_celsius, temp_fahrenheit = kelvin_to_celsius_fahrenheit(temp_kelvin)
feels_like_kelvin = response['main']['feels_like']
feels_like_celsius, feels_like_fahrenheit = kelvin_to_celsius_fahrenheit(feels_like_kelvin)
wind_speed = response['wind']['speed']
humidity = response['main']['humidity']
description = response['weather'][0]['description']
sunrise_time = dt.datetime.utcfromtimestamp(response['sys']['sunrise'] + response['timezone'])
sunset_time = dt.datetime.utcfromtimestamp(response['sys']['sunset'] + response['timezone'])

print(f"Temperature in {CITY}(in celsius unit): {temp_celsius:.2f}°C")
print(f"Temperature in {CITY}(in kelvin unit): {temp_kelvin:}°K")
print(f"Temperature in {CITY}(in fahrenheit unit): {temp_fahrenheit:.2f}°F")
print(f"Humidity in {CITY}: {humidity}%")
print(f"Wind Speed in {CITY}: {wind_speed} m/s")
print(f"Description: {description}")
print(f"Sun rises in {CITY} at {sunrise_time} local time.")
print(f"Sun sets in {CITY} at {sunset_time} local time.")

In [ ]:
import numpy as np

p = np.array([[1, 5],[3, 7],[4, 9]])

np.reshape(p, -1)

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('marks_1.csv', sep = '|', header = None)
df

     0        1            2   3   4   5
0    1   Akshay  Mathematics  50  40  80
1    2   Mahima      English  40  33  83
2    3    Vikas  Mathematics  50  42  84
3    4  Abhinav      English  40  31  78
4    5   Mahima      Science  50  40  80
5    6   Akshay      Science  50  49  98
6    7  Abhinav  Mathematics  50  47  94
7    8    Vikas      Science  50  40  80
8    9  Abhinav      Science  50  47  94
9   10    Vikas      English  40  39  98
10  11   Akshay      English  40  35  88
11  12   Mahima  Mathematics  50  43  86

In [ ]:
import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv'
# Provide your answer below
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep = '|', header = None, index_col = 0)# Write your answer here
df.columns = ['Name', 'Subject', 'Maximum Marks', 'Marks Obtained', 'Percentage']
df.index.name = 'S.No.'
print(df)

          Name      Subject  Maximum Marks  Marks Obtained  Percentage
S.No.
1       Akshay  Mathematics             50              40          80
2       Mahima      English             40              33          83
3        Vikas  Mathematics             50              42          84
4      Abhinav      English             40              31          78
5       Mahima      Science             50              40          80
6       Akshay      Science             50              49          98
7      Abhinav  Mathematics             50              47          94
8        Vikas      Science             50              40          80
9      Abhinav      Science             50              47          94
10       Vikas      English             40              39          98
11      Akshay      English             40              35          88
12      Mahima  Mathematics             50              43          86

In [ ]:
import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv'
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv', index_col = [2,1] )
# Provide your answer below
df.sort_index(inplace=True)
print(df.head())

                         ID  Rating
Office    Department
Bangalore Finance     U2F53     2.7
          Finance     U1F53     3.7
          Finance     U1F28     3.2
          Finance     U1F15     3.3
          Finance     U1F14     2.9

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
#Type your code for describing the dataset
print(df.describe())
#Type your code for printing the columns of the dataset)
print(df.columns)
#Type your code for printing the shape of the dataset)
print(df.shape)

                X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000

             temp          RH        wind        rain         area
count  517.000000  517.000000  517.000000  517.000000   517.000000
mean    18.889168   44.288201    4.017602    0.021663    12.847292
std      5.806625   16.317469    1.791653    0.295959    63.655818
min      2.200000   15.000000    0.400000    0.000000     0.000000
25%     15.500000   33.000000    2.700000    0.000000     0.000000
50%     19.300000   42.000000    4.000000    0.000000     0.520000
75%     22.800000   53.000000    4.900000    0.000000     6.570000
max     33.300000  100.000000    9.400000    6.400000  1090.840000
Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')
(517, 13)

In [ ]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_2 = df[['month','day','temp','area']]#Type your code for selecting columns 'month', 'day' , 'temp' , 'area'
print(df_2.head(20))

   month  day  temp  area
0    mar  fri   8.2   0.0
1    oct  tue  18.0   0.0
2    oct  sat  14.6   0.0
3    mar  fri   8.3   0.0
4    mar  sun  11.4   0.0
5    aug  sun  22.2   0.0
6    aug  mon  24.1   0.0
7    aug  mon   8.0   0.0
8    sep  tue  13.1   0.0
9    sep  sat  22.8   0.0
10   sep  sat  17.8   0.0
11   sep  sat  19.3   0.0
12   aug  fri  17.0   0.0
13   sep  mon  21.3   0.0
14   sep  wed  26.4   0.0
15   sep  fri  22.9   0.0
16   mar  sat  15.1   0.0
17   oct  mon  16.7   0.0
18   mar  wed  15.9   0.0
19   apr  sat   9.3   0.0

In [ ]:
dataframe.loc[[list_of_row_labels], [list_of_column_labels]]
dataframe.iloc[rows, columns]

In [ ]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_2 = df.iloc[2::2, :]#Type your code here for indexing the dataframe
print(df_2.head(20))

    X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
10  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
12  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
14  6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0
16  5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.0
18  6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.0
20  6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.0
22  7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.0
24  7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.0
26  7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.0
28  6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.0
30  6  3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   0.0   0.0
32  6  3   sep  fri  88.6   69.7  706.8   5.8  20.6  37   1.8   0.0   0.0
34  6  3   sep  mon  91.8   78.5  724.3   9.2  21.2  32   2.7   0.0   0.0
36  6  3   oct  tue  90.6   35.4  669.1   6.7  21.7  24   4.5   0.0   0.0
38  7  3   oct  sat  90.6   43.7  686.9   6.7  17.8  27   4.0   0.0   0.0
40  4  4   jul  tue  79.5   60.6  366.7   1.5  23.3  37   3.1   0.0   0.0

In [ ]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_2 = df[ (df['area'] > 0) & (df['wind'] > 1) & (df['temp'] > 15) ]
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0  0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0  0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0  0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0  0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0  0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0  0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0  0.90
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0  0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0  1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0  1.12
150  6  5   jun  fri  92.5   56.4  433.3   7.1  23.2  39   5.4   0.0  1.19
151  9  9   jul  sun  90.1   68.6  355.2   7.2  24.8  29   2.2   0.0  1.36
152  3  4   jul  sat  90.1   51.2  424.1   6.2  24.6  43   1.8   0.0  1.43
153  5  4   sep  fri  94.3   85.1  692.3  15.9  20.1  47   4.9   0.0  1.46
154  1  5   sep  sat  93.4  145.4  721.4   8.1  29.6  27   2.7   0.0  1.46
155  7  4   aug  sun  94.8  108.3  647.1  17.0  16.4  47   1.3   0.0  1.56
156  2  4   sep  sat  93.4  145.4  721.4   8.1  28.6  27   2.2   0.0  1.61
157  2  2   aug  wed  92.1  111.2  654.1   9.6  18.4  45   3.6   0.0  1.63
158  2  4   aug  wed  92.1  111.2  654.1   9.6  20.5  35   4.0   0.0  1.64

Employee Training
Description
You are provided with the dataset of a company which has offices across three cities - Mumbai, Bangalore and New Delhi. The dataset contains the rating (out of 5) of all the employees from different departments (Finance, HR, Marketing and Sales). 



The company has come up with a new policy that any individual with a rating equal to or below 3.5 needs to attend a training. Using dataframes, load the dataset and then derive the column ‘Training’ which shows ‘Yes’ for people who require training and ‘No’ for those who do not.



Print the first 5 rows as the output. Refer to the image below for your reference.





Note: You should not sort or modify values in other columns of the dataframe.

In [3]:
import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv'
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')

# Provide your answer below
df["Training"] = df.Rating.apply(lambda x: "No" if x > 3.5  else "Yes")
print(df.head())

      ID Department     Office  Rating Training
0  U2F26    Finance  New Delhi     3.4      Yes
1  U2M61  Marketing  New Delhi     3.9       No
2  U1S15      Sales  New Delhi     2.8      Yes
3  U1H87         HR     Mumbai     2.1      Yes
4  U1S51      Sales  New Delhi     4.6       No

In [17]:
good = df[df["Training"] == "No" ]

print(len(good[good['Department']== 'Marketing']) / len(df[df['Department']== 'Marketing']))
print(len(good[good['Department']== 'Finance']) / len(df[df['Department']== 'Finance']))
print(len(good[good['Department']== 'HR']) / len(df[df['Department']== 'HR']))
print(len(good[good['Department']== 'Sales']) / len(df[df['Department']== 'Sales']))

0.4492753623188406
0.4925373134328358
0.5572519083969466
0.46153846153846156

In [18]:
df.groupby()

TypeError: ignored

In [23]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
#Type your groupby command here
df_by = df.groupby(by = ['month', 'day'])
df_1 = df_by['rain', 'wind'].mean()
print(df_1.head(20))

               rain      wind
month day
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """

In [ ]:
dataframe_1.merge(dataframe_2, on = ['column_1', 'column_2'], how = '____')